// TODO: #1 move from 24x24 to 16x16

export { AtIcon } from './AtIcon'
export { ChatIcon } from './ChatIcon'
export { DiscordIcon } from './DiscordIcon'
export { EyeClosedIcon } from './EyeClosedIcon'
export { EyeOpenIcon } from './EyeOpenIcon'
export { GithubIcon } from './GithubIcon'
export { HeartIcon } from './HeartIcon'
export { InboxIcon } from './InboxIcon'
export { LinkedinIcon } from './LinkedinIcon'
export { LockIcon } from './LockIcon'
export { MenuIcon } from './MenuIcon'
export { MoonIcon } from './MoonIcon'
export { PasswordIcon } from './PasswordIcon'
export { PinIcon } from './PinIcon'
export { PlanetIcon } from './PlanetIcon'
export { RedoIcon } from './RedoIcon'
export { SendIcon } from './SendIcon'
export { SettingsIcon } from './SettingsIcon'
export { SunIcon } from './SunIcon'
export { ToolsIcon } from './ToolsIcon'
export { TrashIcon } from './TrashIcon'
export { TwitterIcon } from './TwitterIcon'
export { UndoIcon } from './UndoIcon'
export { UnlockIcon } from './UnlockIcon'
export { WritingIcon } from './WritingIcon'
export { YouTubeIcon } from './YoutubeIcon'